/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_avatarcn_lame_AvatarLameMp3 */

#ifndef _Included_com_avatarcn_lame_AvatarLameMp3
#define _Included_com_avatarcn_lame_AvatarLameMp3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_avatarcn_lame_AvatarLameMp3
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_avatarcn_lame_AvatarLameMp3_getVersion
        (JNIEnv *, jobject);

/*
 * Class:     com_avatarcn_lame_AvatarLameMp3
 * Method:    init
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_avatarcn_lame_AvatarLameMp3_init
        (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_avatarcn_lame_AvatarLameMp3
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_avatarcn_lame_AvatarLameMp3_encode
        (JNIEnv *, jobject, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_avatarcn_lame_AvatarLameMp3
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_avatarcn_lame_AvatarLameMp3_flush
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_avatarcn_lame_AvatarLameMp3
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_avatarcn_lame_AvatarLameMp3_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
